version: "3.8"
services:
  website:
    build: "./frontend"
    ports:
      - "3000:80"

  auth:
    build: "./backend/auth-service"
    ports:
      - "5000:5000"
    networks:
      - backend
    environment:
      - production=docker

  server:
    build: "./backend/server"
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      - production=docker

  mongodb:
    image: mongo:3.6.21
    restart: always
    networks:
      - backend
    environment:
      MONGO_INITDB_DATABASE: "quizmaster"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - database:/var/lib/mongodb

networks:
  backend:

volumes:
  database:
